### ISSUE TITLE
Timer is slow...

### ISSUE THREAD

**Issue by ZWhiteShadow** [WadeTheWhiteShadow/ScreenTime#3]

**Comment by WadeTheWhiteShadow** [comment]
var start = Date.now();
setInterval(function() {
    var delta = Date.now() - start; // milliseconds elapsed since start
    …
    output(Math.floor(delta / 1000)); // in seconds
    // alternatively just show wall clock time:
    output(new Date().toUTCString());
}, 1000); // update about every second

Possible solution

**Comment by ZWhiteShadow** [comment]
Solved using the previous code
